name: Desplegament a producció Windows

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout del codi
      uses: actions/checkout@v3
      
    - name: Desplegament via SSH (Windows)
    uses: appleboy/ssh-action@v0.1.10
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      script: |
        # Comandes PowerShell via SSH
        powershell -Command "
          cd C:\inetpub\wwwroot\a23albrobfon;
          Remove-Item * -Recurse -Force;
          Copy-Item -Path C:\temp\gh_actions\* -Destination . -Recurse;
        "