name: Desplegament a producció Windows

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout del codi
      uses: actions/checkout@v3
      
    - name: Desplegament via WinRM (PowerShell)
      uses: appleboy/winrm-action@v0.4.0
      with:
        host: ${{ secrets.WINRM_HOST }}  # Adreça IP o domini
        username: ${{ secrets.WINRM_USERNAME }}
        password: ${{ secrets.WINRM_PASSWORD }}  # O usa key si tens certificats
        port: ${{ secrets.WINRM_PORT || 5986 }}  # 5986 per HTTPS
        script: |
          # 1. Anar al directori de producció (ruta Windows)
          cd C:\inetpub\wwwroot\a23albrobfon
          
          # 2. Eliminar contingut anterior (PowerShell)
          Remove-Item * -Recurse -Force
          
          # 3. Copiar nous arxius (des de la màquina local)
          Copy-Item -Path "$env:GITHUB_WORKSPACE\*" -Destination . -Recurse -Force
          
          # 4. Instal·lar dependències (si és Node.js)
          npm install --production
          
          # 5. Configurar permisos (opcional)
          icacls . /grant "IIS_IUSRS:(OI)(CI)F"